# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# XDC: new/Zybo-Master.xdc

# Block Designs: bd/design_2/design_2.bd
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_2 || ORIG_REF_NAME==design_2} -quiet] -quiet

# IP: bd/design_2/ip/design_2_processing_system7_0_0/design_2_processing_system7_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_2_processing_system7_0_0 || ORIG_REF_NAME==design_2_processing_system7_0_0} -quiet] -quiet

# IP: bd/design_2/ip/design_2_axi_gpio_0_0/design_2_axi_gpio_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_2_axi_gpio_0_0 || ORIG_REF_NAME==design_2_axi_gpio_0_0} -quiet] -quiet

# IP: bd/design_2/ip/design_2_axi_gpio_1_0/design_2_axi_gpio_1_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_2_axi_gpio_1_0 || ORIG_REF_NAME==design_2_axi_gpio_1_0} -quiet] -quiet

# IP: bd/design_2/ip/design_2_axi_gpio_2_0/design_2_axi_gpio_2_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_2_axi_gpio_2_0 || ORIG_REF_NAME==design_2_axi_gpio_2_0} -quiet] -quiet

# IP: bd/design_2/ip/design_2_axi_gpio_3_0/design_2_axi_gpio_3_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_2_axi_gpio_3_0 || ORIG_REF_NAME==design_2_axi_gpio_3_0} -quiet] -quiet

# IP: bd/design_2/ip/design_2_axi_gpio_4_0/design_2_axi_gpio_4_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_2_axi_gpio_4_0 || ORIG_REF_NAME==design_2_axi_gpio_4_0} -quiet] -quiet

# IP: bd/design_2/ip/design_2_axi_gpio_5_0/design_2_axi_gpio_5_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_2_axi_gpio_5_0 || ORIG_REF_NAME==design_2_axi_gpio_5_0} -quiet] -quiet

# IP: bd/design_2/ip/design_2_axi_smc_1/design_2_axi_smc_1.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_2_axi_smc_1 || ORIG_REF_NAME==design_2_axi_smc_1} -quiet] -quiet

# IP: bd/design_2/ip/design_2_rst_ps7_0_50M_1/design_2_rst_ps7_0_50M_1.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_2_rst_ps7_0_50M_1 || ORIG_REF_NAME==design_2_rst_ps7_0_50M_1} -quiet] -quiet

# IP: bd/design_2/ip/design_2_top_onn_system_wrapp_0_1/design_2_top_onn_system_wrapp_0_1.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_2_top_onn_system_wrapp_0_1 || ORIG_REF_NAME==design_2_top_onn_system_wrapp_0_1} -quiet] -quiet

# XDC: c:/Users/riyan/ONN_Final_Implementation/ONN_Final_Implementation.gen/sources_1/bd/design_2/design_2_ooc.xdc
